### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by FortreeForums** [cmende/scmpc#11]
ive been trying to compile this under cygwin but keep hitting this error:
mpc.exe scmpc-audiscrobber.o scmpc-mpd.o scmpc-msc.o scmpc-preferences.o scmpc-queue.o scmpc-scmpc.o -lglib-2.0 -lintl /usr/local -lcurl -lmpdclient
/usr/local: file not recognized: Is a directory
collect2: error: ld returned 1 exit status

when i look in the makefile, it seems to be this line giving the problem: 
confuse_LIBS = /usr/local

any help is greatly appreciated

**Comment by nyxdis** [comment]
Which version are you trying to compile? Did you try git master?

**Comment by nyxdis** [comment]
I just tried to compile scmpc on cygwin using x86_64-pc-cygwin-gcc and it worked fine, so I need more information about your build environment.

**Comment by FortreeForums** [comment]
i'm trying to compile with the latest commit, as well as the latest versions of GCC. i think cygwin had trouble finding the confuse libs, because i have to set confuse_LIBS="/usr/local" when running ./configure. if i don't set that value this is the error https://puu.sh/u63wH/62fe898c92.png

**Comment by nyxdis** [comment]
Well, that's not how you're supposed to use `confuse_LIBS`. The help says `linker flags for confuse, overriding pkg-config`. "/usr/local/" is not a valid linker flag (as opposed to `-lconfuse` for example). But instead of using `confuse_LIBS` to hack around pkgconfig not finding libconfuse, you could also help pkgconfig finding it.
Try `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ ./configure`

**Comment by FortreeForums** [comment]
that last line seemed to get it working, thanks!
